### ISSUE TITLE
Marshaled xml root tag is always starting with uppercase

### ISSUE THREAD

**Issue by meblum** [twpayne/go-xmlstruct#28]
Generating structs from
```xml
<parent>
  <child>childValue</child>
</parent>
```
produces
```go
type Parent struct {
        Child string `xml:"child"`
}
```
Which marshals as xml with an uppercase root tag (notice the uppercase `P`) [playground](https://go.dev/play/p/MrD18A00BnI)
```xml
<Parent>
   <child>childValue</child>
</Parent>
```
Ideally, the root struct should contain an `xml.Name` field to preserve the proper xml name.
This will also allow the user to rename the root struct without affecting the xml output

**Comment by twpayne** [comment]
Thanks for spotting and reporting. `v1.5.0` includes a `WithNamedRoot` option to include an `XMLName` in the generated root struct.

**Comment by meblum** [comment]
@twpayne the import statement should not be included when package name is empty.

**Comment by twpayne** [comment]
> @twpayne the import statement should not be included when package name is empty.

You're right, thanks. However, there's a more to this issue. If one of the generated fields is a `time.Time` then an `import "time"` statement will be included when the package name is empty. This is because the current code to strip the package name is too simple. Could you open a separate issue for this?
